### ISSUE TITLE
[Suggestion] Show compendium source in results

### ISSUE THREAD

**Issue by siliconsaint** [League-of-Foundry-Developers/compendium-browser#11]
It's common to have multiple versions of a spell/item. It would be helpful to see the source Compendium in the results along with the search results to determine which flavor I'm trying to find (the DAE, the ItemMacro version etc).

Perhaps I have a module interfering, but I cannot see that in the results?

**Comment by spetzel2020** [comment]
Thanks for the suggestion and I'll take a look!

**Comment by spetzel2020** [comment]
Planned for 0.4.4

**Comment by siliconsaint** [comment]
Thanks so much!!  I'll be looking for it!

**Comment by spetzel2020** [comment]
The easiest way for me to do this is a hack to overload the image hover title:

![image](https://user-images.githubusercontent.com/10853466/111217049-57d18380-8592-11eb-9d78-1eb1aa573506.png)

As you can see, part of the challenge is that the compendium name can be very long. Possible approaches:
1. This one on hovering over the item image
2. Display the compendium name in the list which will be very busy
3. Display the compendium name when you click though an (i) info link for details

What do you think?

**Comment by siliconsaint** [comment]
Thanks so much for gathering input. I never considered all these options, but they make sense.  I think your intuition for hovering over image is the best one, as it doesn't clutter the listing, and it's super quick.  I think the only problem might be that folks will not know they can do it!

**Comment by spetzel2020** [comment]
Thanks for the quick response!

I just realized that a tooltip over the name makes more sense, because that's where you click to get the full info:
![image](https://user-images.githubusercontent.com/10853466/111218473-00341780-8594-11eb-9200-a00543df9c28.png)

I'll go ahead and implement it like this and see what reaction it gets (if any)

**Comment by siliconsaint** [comment]
Sounds great to me!  Looking forward to the update, thanks for including it!

**Comment by spetzel2020** [comment]
Released in 0.4.5; either update or use https://github.com/League-of-Foundry-Developers/compendium-browser/releases/download/latest/module.json
