### ISSUE TITLE
Pathfinder/D&D 3.5 support?

### ISSUE THREAD

**Issue by irbian** [League-of-Foundry-Developers/compendium-browser#16]
Would be too difficult?

**Comment by spetzel2020** [comment]
Interesting. In theory I think it's quite doable, given that the searched compendia are already listed. I will take a look at what I see if I fire up Pathfinder in Foundry.

**Comment by irbian** [comment]
Actually the 3.5 system looks like recently added some kind of compendium searcher included 🤔

**Comment by spetzel2020** [comment]
Yep, and given that it has I personally would not plan on adding anything to this module.
