### ISSUE TITLE
I keep getting a console error when I attempt to filter NPCs by Creature Type (filed by @bitkiller0)

### ISSUE THREAD

**Issue by spetzel2020** [League-of-Foundry-Developers/compendium-browser#17]
I keep getting a console error when I attempt to filter NPCs by Creature Type: Uncaught (in promise) TypeError: prop.toLowerCase is not a function
    at CompendiumBrowser.passesFilter (compendium-browser.js:1151)
    at compendium-browser.js:713
    at async CompendiumBrowser.loadAndFilterNpcs (compendium-browser.js:708)
    at async CompendiumBrowser.renderItemData (compendium-browser.js:863)
    at async CompendiumBrowser.replaceList (compendium-browser.js:836)
passesFilter    @    compendium-browser.js:1151
(anonymous)    @    compendium-browser.js:713
async function (async)        
replaceList    @    compendium-browser.js:836
(anonymous)    @    compendium-browser.js:341
dispatch    @    jquery.min.js:2
v.handle    @    jquery.min.js:2
ListPicker._handleMouseUp    @    unknown  The JS hangs and the NPC Browser stops responding.  Is this a known issue?

**Comment by spetzel2020** [comment]
The problem appears to be related to `data.details.type` now being a structure rather than a text string; the correct property in 0.8.x would be `data.details.type.value`

There may be other filters that need to be adjusted for 0.8,x

**Comment by RufusTiki** [comment]
I'm getting a different error in 0.5.0 when filtering by creature type:

```
helpers.mjs:276 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'value' in Monstrosity
    at getProperty (helpers.mjs:276)
    at CompendiumBrowser.passesFilter (compendium-browser.js:1138)
    at compendium-browser.js:714
    at async CompendiumBrowser.loadAndFilterNpcs (compendium-browser.js:709)
    at async CompendiumBrowser.renderItemData (compendium-browser.js:864)
    at async CompendiumBrowser.replaceList (compendium-browser.js:837)
```

Foundry 0.8.8, everything updated.

Though I'm not getting this error on my local Foundry install, just on our GM's server, so perhaps it has to do with his compendiums. (He has some using DDB Muncher and I don't...). I will try to investigate further....

**Comment by RufusTiki** [comment]
Ok, actually turning off "Supplemental Bestiary" made the errors go away. Is this an issue I should report over there? I guess I will wait and see if it's something on your end. Thanks! 
https://github.com/sparkcity/fvtt-supplementalbestiary

**Comment by spetzel2020** [comment]
I'll take a look later today - thanks for the report!

**Comment by spetzel2020** [comment]
I'm 99% sure that the problem is that Supplemental Bestiary has not been updated for the Foundry 0.8 data model changes. `data.details.type` has now become a structure and now needs to be `data.details.type.value`. COmpendium Browser checks for the FOundry version and looks for the appropriate property.

**Comment by RufusTiki** [comment]
Ah ok! Do you happen to know an easy way to update it myself? I tried copying the compendium in hopes that it would update it, but doesn't seem to have helped. Looking for documentation on compendiums and 8.x but not easy to find as usual....
I will open an issue over there in any case. thanks.
