### ISSUE TITLE
Support for CompendiumCollection#getContent will be removed in 0.9.0.

### ISSUE THREAD

**Issue by Doresain** [League-of-Foundry-Developers/compendium-browser#19]
Hey, great module! 

This is just a warning in the console now, but thought I'd drop it here for tracking so it doesn't get lost for 0.9.0:

"You are calling CompendiumCollection#getContent which has been renamed to of CompendiumCollection#getDocuments. Support will be removed in 0.9.0."

**Comment by spetzel2020** [comment]
PR #24 addresses this and will be merged to a new release 0.7, supporting only Foundry 0.8.x and up.
