### ISSUE TITLE
Drag'n'Drop doesn't work with Foundry 9

### ISSUE THREAD

**Issue by TheKarubian** [League-of-Foundry-Developers/compendium-browser#29]
Since the update to Foundry 9, drag'n'drop from the browser into the sidebar doesn't work any longer. I can still drag an item (e.g. an NPC) out of the compendium browser, but the sidebar doesn't accept it when I try dropping it (e.g. as an actor).

**Comment by mark-d-holmberg** [comment]
It also doesn't work if you try and drag a spell from the compendium onto a character sheet.

**Comment by spetzel2020** [comment]
I'm pretty sure I know how to fix this - should be straightforward.

**Comment by spetzel2020** [comment]
Fixed in 0.7.2 (replaced pack.entity with pack.documentName)
