### ISSUE TITLE
Wrong spell names in code

### ISSUE THREAD

**Issue by TheForster585** [League-of-Foundry-Developers/compendium-browser#30]
Hello. The Spell Summon Shadowspawn is written as summon shadowPawn in the code. Please, fix.
Also, I noticed that the spell Dream of the Blue Veil misses all the classes except Bard.

**Comment by spetzel2020** [comment]
> Hello. The Spell Summon Shadowspawn is written as summon shadowPawn in the code. Please, fix. 
Fixed in 0.7.2 in `spell-classes.json`

>Also, I noticed that the spell Dream of the Blue Veil misses all the classes except Bard.
Fixed in 0.7.2; was duplicated in `spell-classes.json`, the second time incorrectly

**Comment by spetzel2020** [comment]
Fixed in 0.7.2
