### ISSUE TITLE
Abandoned or is V10 support going to happen? 

### ISSUE THREAD

**Issue by joevaughan** [League-of-Foundry-Developers/compendium-browser#39]
Question: Is this abandoned? - Hasn't been updated since Jan and bugs open since then.

If not abandoned: Is someone looking at V10 support/changes? I don't think it will take a great deal as compendiums haven't had massive core changes in V10 (unlike, e.g. Journals).

**Comment by spetzel2020** [comment]
Although I don't "own" this, I think I'm the one who's been maintaining
compatibility. Unfortunately I have my hands full with bringing Quick
Encounters up-to-date which is consuming all my time (because of the
Journal changes).

**Comment by joevaughan** [comment]
Thanks for all your hard work @spetzel2020 (and all or the League :D)

FWIW: I forked and simply updated the module.json to enable compatability with v10 and I would say it appears to be 95% functioning (I've only come across one weird error which I haven't yet been able to verify is definitely a bug or a consequence of my environment/foundry-setup)

Will continue my 'hacky' messing around with same. Was just curious if I was wasting my time (i.e. is someone already doing this).

**Comment by bradleyquinn** [comment]
I appreciate anyone that is willing to bring this up to v10 support.  I am completely lost without it.

**Comment by spetzel2020** [comment]
Thanks Joe. Ping me directly (spetzel#0103 on Discord) if nobody responds
promptly after you submit the PR.

**Comment by Alixzer** [comment]
I took a look at it myself, but unfortunately my brain falls apart when it comes to this kind of stuff.  Good luck to fixing it, as the only feature I use out of it for my games is the npc browser

**Comment by joevaughan** [comment]
Apologies. Was Flu'ed up since Friday. Submitted PR today. Hopefully works (definitely works for me :D)

**Comment by joevaughan** [comment]
@Alixzer, @bradleyquinn - Just to say: @spetzel2020 has merged the v10 code into the main branch now and will do a release some time soon (but please just have a little more patience as he's not at home at the moment - is in a whole other timezone - so doing a build and release isn't easy). Once he does that release I'll close this.

**Comment by joevaughan** [comment]
V10 supporting release (0.8.1) published by @spetzel2020 on Sept 16th. Closing.
