### ISSUE TITLE
Prevent requests on every input change by adding a short delay.

### ISSUE THREAD

**Issue by Oshcakes** [League-of-Foundry-Developers/compendium-browser#7]
If the user types several keys without allowing 200ms - 500ms (example) to pass between them, then those keys are sent together in one request. 

As it is now the search is rather slow with large compendiums, it appears there are multiple searches happening that could be reduced.

**Comment by Oshcakes** [comment]
Or add search button so the user can control when the search happens.

**Comment by spetzel2020** [comment]
Yep, completely agree; this behavior was acceptable when the Compendium was all in-memory, but now needs to be managed.

**Comment by spetzel2020** [comment]
I believe this will be addressed by PR #24 which stops the old search when a new one is started, but am confirming.

**Comment by spetzel2020** [comment]
Released in [Release v0.7.0](https://github.com/League-of-Foundry-Developers/compendium-browser/releases/tag/v0.7.0)

I will create an Enhancement request for a Search button in case this release doesn't completely address the problem
